In [1]:
import numpy as np

In [2]:
x = np.array([10, 14, 19])

In [3]:
y = [10, 14, 19]

In [4]:
y_2 = y*2
print(y_2)

[10, 14, 19, 10, 14, 19]


In [5]:
x_2 = x*2
print(x_2)

[20 28 38]


In [7]:
x1 = np.zeros(3)
x2 = np.ones((2,3))

print(x1)
print(x2)

[0. 0. 0.]
[[1. 1. 1.]
 [1. 1. 1.]]


In [8]:
x3 = np.random.rand(2, 3)

In [9]:
print(x3)

[[0.05741088 0.82181383 0.31318222]
 [0.56933904 0.49781134 0.54679554]]
